---

- name: establish pre-requisites
  apt:
    name:
      - gnupg-agent
      - apt-transport-https

- name: add apt repository key
  become: true
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"   # noqa 204
    state: present

- name: add apt repository
  become: true
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /"
    filename: buildah
